#spring.application.name=joo-hee
project:
  name: joo-hee
  description: 클래스 예약 서비스 제공

app:
  home: app-home

####################################################################

server:
  id: ${HOSTNAME:local}
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
    context-path: /
  # tomcat access log
  tomcat:
    basedir: ${app.home:.}
    access-log:
      enabled: true
      directory: ${app.home:.}/logs/${logging.module}/
      prefix: ${server.id}-access                     # hostname (pod name)
      pattern: '%h %l %u %t "%r" %s %{User-Agent}i %{Referer}i %b %D'

####################################################################

spring:
  application:
    name: ${project.name}
  pid:
    file: ${app.home}/bin/shutdown.pid
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  jpa:
    properties:
      hibernate:
        format_sql: true

  ####################################################################

  datasource:
    url: jdbc:mysql://db-pdp6e.pub-cdb.ntruss.com:13306/joohee
    username: admin
    password: test
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      idle-timeout: 240000 #4min

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    cache-enabled: false
    use-column-label: true
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    lazy-loading-enabled: true
    call-setters-on-nulls: true

####################################################################

jasypt:
  encryptor:
    password: joohee
    bean: encryptorBean

####################################################################

logging:
  module: "main"
  file:
    name: ${app.home:.}/logs/${logging.module}/${server.id}-service.log
  pattern:
    console: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} [%-48.48logger{47}:%4line] %m%n"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} [%-48.48logger{47}:%4line] %m%n"
  logback:
    rolling-policy:
      file-name-pattern: ${app.home}/logs/${logging.module}/%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 50MB
      max-history: 30
  level:
    ROOT: DEBUG
    org.springframework: INFO
    org.springframework.web: ERROR
    org.apache: ERROR
    com.flab: DEBUG
